os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_REFERENCE="OGRE/1.9.0"
    - CONAN_USERNAME="hilborn"
    - CONAN_CHANNEL="stable"
    - CONAN_TOTAL_PAGES=3

  matrix:
    - CONAN_GCC_VERSIONS=4.6 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=1
    - CONAN_GCC_VERSIONS=4.6 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=2
    - CONAN_GCC_VERSIONS=4.6 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=3

    - CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=1
    - CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=2
    - CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=3

    - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=1
    - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=2
    - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=3

    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=1
    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=2
    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=3

    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=1
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=2
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=3

    - CONAN_GCC_VERSIONS=5.4 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=1
    - CONAN_GCC_VERSIONS=5.4 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=2
    - CONAN_GCC_VERSIONS=5.4 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=3

    - CONAN_GCC_VERSIONS=6.2 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=1
    - CONAN_GCC_VERSIONS=6.2 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=2
    - CONAN_GCC_VERSIONS=6.2 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=3
matrix:
   include:
       - os: osx
         osx_image: xcode8 # apple-clang 8.0
         language: generic
         env: CONAN_CURRENT_PAGE=1
       - os: osx
         osx_image: xcode8
         language: generic
         env: CONAN_CURRENT_PAGE=2
       - os: osx
         osx_image: xcode8
         language: generic
         env: CONAN_CURRENT_PAGE=3

       - os: osx
         osx_image: xcode7.3 # apple-clang 7.3
         language: generic
         env: CONAN_CURRENT_PAGE=1
       - os: osx
         osx_image: xcode7.3
         language: generic
         env: CONAN_CURRENT_PAGE=2
       - os: osx
         osx_image: xcode7.3
         language: generic
         env: CONAN_CURRENT_PAGE=3

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
  
